from __future__ import annotations

from pipeline_core.domain_profile import (
    CorpusSemantics,
    DEFAULT_STRONG_CAUSAL_TEXT_PATTERNS,
    DiscoverySemantics,
    NoveltySemantics,
    ResolutionSemantics,
    ScientificDomainProfile,
)


CATALYSIS_MECHANISM_PROFILE = ScientificDomainProfile(
    profile_id="catalysis_mechanism",
    description=(
        "Broad heterogeneous/electrocatalysis mechanism profile for "
        "abstract-level cross-domain discovery and later federation with "
        "target-domain evidence corpora."
    ),
    resolution=ResolutionSemantics(
        resolvable_node_types=frozenset({
            "Paper",
            "Catalyst",
            "CatalystModel",
            "Metal",
            "Support",
            "CoordinationMotif",
            "Reaction",
            "ReactionStep",
            "Intermediate",
            "Material",
            "SynthesisMethod",
            "Precursor",
            "ActiveSite",
            "StructuralState",
            "AdsorbateState",
            "InterfacialEnvironment",
            "MechanisticFactor",
            "Descriptor",
            "Experiment",
            "Calculation",
        }),
        auto_merge_types=frozenset({"Metal", "Reaction"}),
        text_replacements=(
            ("hydrogen evolution reaction", "her"),
            ("hydrogen oxidation reaction", "hor"),
            ("oxygen evolution reaction", "oer"),
            ("oxygen reduction reaction", "orr"),
            ("carbon dioxide reduction reaction", "co2rr"),
            ("co2 reduction reaction", "co2rr"),
            ("nitrogen reduction reaction", "nrr"),
            ("single atoms", "single atom"),
            ("dual atoms", "dual atom"),
            ("active sites", "active site"),
            ("rate determining step", "rate-determining step"),
            ("rate-limiting step", "rate-determining step"),
        ),
        reaction_aliases=(
            ("her", "hydrogen_evolution_reaction"),
            ("hydrogen evolution", "hydrogen_evolution_reaction"),
            ("hydrogen evolution reaction", "hydrogen_evolution_reaction"),
            ("hor", "hydrogen_oxidation_reaction"),
            ("hydrogen oxidation", "hydrogen_oxidation_reaction"),
            ("hydrogen oxidation reaction", "hydrogen_oxidation_reaction"),
            ("orr", "oxygen_reduction_reaction"),
            ("oxygen reduction reaction", "oxygen_reduction_reaction"),
            ("oer", "oxygen_evolution_reaction"),
            ("oxygen evolution reaction", "oxygen_evolution_reaction"),
            ("co2rr", "carbon_dioxide_reduction_reaction"),
            ("co2 reduction reaction", "carbon_dioxide_reduction_reaction"),
            ("nrr", "nitrogen_reduction_reaction"),
            ("nitrogen reduction reaction", "nitrogen_reduction_reaction"),
        ),
        support_signature_tokens=frozenset({
            "graphene",
            "carbon",
            "nitrogen",
            "oxide",
            "nitride",
            "carbide",
            "sulfide",
            "phosphide",
            "alloy",
            "support",
        }),
        high_priority_review_types=frozenset({
            "Catalyst",
            "CatalystModel",
            "Support",
            "CoordinationMotif",
            "ActiveSite",
            "StructuralState",
            "AdsorbateState",
            "InterfacialEnvironment",
            "MechanisticFactor",
            "Descriptor",
        }),
    ),
    discovery=DiscoverySemantics(
        generic_entity_types=frozenset({
            "CATALYST",
            "CATALYSTMODEL",
            "MATERIAL",
            "SUPPORT",
            "METAL",
            "REACTION",
            "ACTIVESITE",
            "STRUCTURALSTATE",
            "ADSORBATESTATE",
            "INTERFACIALENVIRONMENT",
            "MECHANISTICFACTOR",
            "DESCRIPTOR",
        }),
        mechanism_node_markers=(
            "MECHANISM",
            "MECHANISTIC",
            "ACTIVESITE",
            "STRUCTURALSTATE",
            "ADSORBATESTATE",
            "INTERFACIALENVIRONMENT",
        ),
        mechanism_relation_markers=(
            "INTERPRETED_AS",
            "INDUC",
            "MODULAT",
            "STABIL",
            "DESTABIL",
            "PROMOT",
            "SUPPRESS",
            "FACILITAT",
            "INHIBIT",
            "RECONSTRUCT",
            "CHANGES_ACTIVE_SITE",
            "CHANGES_RDS",
            "DEPENDS_ON",
            "CORRELAT",
            "FAILS_WHEN",
            "ADSORB",
            "TRANSFER",
            "COUPL",
        ),
        scaffold_relations=frozenset({
            "STUDIES",
            "HAS_METAL",
            "SUPPORTED_ON",
            "HAS_MOTIF",
            "CATALYZES",
            "MODEL_OF",
            "MODELED_BY",
            "HAS_ACTIVE_SITE",
            "HAS_STRUCTURAL_STATE",
            "HAS_ADSORBATE_STATE",
            "HAS_ENVIRONMENT",
            "HAS_DESCRIPTOR",
            "INVOLVES_STEP",
            "INVOLVES_INTERMEDIATE",
            "APPLIES_TO",
            "ALIGNS_TO_REGISTRY_ENTITY",
            "HAS_PAPER_MENTION",
        }),
        context_node_types=frozenset({
            "REACTION",
            "INTERFACIALENVIRONMENT",
        }),
        shared_entity_types=frozenset({
            "CATALYST",
            "CATALYSTMODEL",
            "MATERIAL",
            "SUPPORT",
            "METAL",
            "COORDINATIONMOTIF",
            "REACTION",
            "REACTIONSTEP",
            "INTERMEDIATE",
            "ACTIVESITE",
            "STRUCTURALSTATE",
            "ADSORBATESTATE",
            "INTERFACIALENVIRONMENT",
            "MECHANISTICFACTOR",
            "DESCRIPTOR",
        }),
        legacy_mechanism_id_prefixes=("mech_",),
        strong_causal_text_patterns=(
            DEFAULT_STRONG_CAUSAL_TEXT_PATTERNS
            + (
                r"\breconstruct(?:s|ed|ing|ion)?\b",
                r"\bswitch(?:es|ed|ing)?\b",
                r"\binhibit(?:s|ed|ing)?\b",
                r"\bsuppress(?:es|ed|ing)?\b",
                r"\bdestabiliz(?:e|es|ed|ing)\b",
            )
        ),
    ),
    corpus=CorpusSemantics(
        semantics_id="catalysis_mechanism_corpus_v1_alpha4b3a",
        review_candidate_types=frozenset({
            "Catalyst",
            "CatalystModel",
            "Support",
            "CoordinationMotif",
            "Material",
            "Intermediate",
        }),
        pattern_alignment_mode="disabled",
        high_priority_review_types_override=frozenset({
            "Catalyst",
            "CatalystModel",
            "Support",
            "Material",
        }),
    ),
    novelty=NoveltySemantics(
        domain_patterns=(
            ("HER", (r"\bher\b", r"hydrogen\s+evolution")),
            ("HOR", (r"\bhor\b", r"hydrogen\s+oxidation")),
            ("ORR", (r"\borr\b", r"oxygen\s+reduction")),
            ("OER", (r"\boer\b", r"oxygen\s+evolution")),
            ("CO2RR", (
                r"\bco2rr\b",
                r"co2\s+(?:electro)?reduction",
                r"carbon\s+dioxide\s+(?:electro)?reduction",
            )),
            ("NRR", (r"\bnrr\b", r"nitrogen\s+reduction")),
            ("CATALYSIS", (
                r"\belectrocatal",
                r"heterogeneous\s+catal",
                r"catalytic\s+(?:activity|mechanism|site)",
            )),
        ),
        scope_patterns=(
            ("working_state", (
                r"working[- ]state",
                r"operando",
                r"reconstruct",
                r"active[- ]site\s+(?:evolution|switch)",
            )),
            ("kinetics", (
                r"rate[- ]determining",
                r"rate[- ]limiting",
                r"activation\s+(?:barrier|energy)",
                r"microkinetic",
                r"constant[- ]potential",
            )),
            ("interface", (
                r"interfacial\s+water",
                r"electric\s+double\s+layer",
                r"cation\s+effect",
                r"hydrogen[- ]bond\s+network",
                r"electrolyte\s+effect",
            )),
            ("structural_landscape", (
                r"energy\s+landscape",
                r"structural\s+state",
                r"coordination\s+(?:environment|motif|geometry)",
                r"metal[- ]metal\s+distance",
            )),
            ("active_site", (
                r"active[- ]site",
                r"site[- ]selective",
                r"poison",
                r"molecular\s+probe",
            )),
            ("cooperative", (
                r"cooperativ",
                r"bifunctional",
                r"dual[- ]site",
                r"bridge\s+adsor",
                r"spillover",
            )),
            ("descriptor_failure", (
                r"descriptor\s+(?:breakdown|failure|limitation)",
                r"scaling\s+(?:relation|break)",
                r"volcano\s+(?:deviation|break)",
            )),
            ("atomic_site", (
                r"single[- ]atom",
                r"dual[- ]atom",
                r"diatomic",
                r"metal[- ]pair",
            )),
        ),
        critical_scope_features=frozenset(),
        claim_context_patterns=(
            r"\belectrocatal",
            r"heterogeneous\s+catal",
            r"active[- ]site",
            r"reaction\s+mechanism",
        ),
        document_mismatch_patterns=(
            r"\bphotocatal",
            r"\bbiocatal",
            r"homogeneous\s+catal",
        ),
        document_compatible_patterns=(
            r"\belectrocatal",
            r"heterogeneous\s+catal",
            r"electrode",
            r"surface",
        ),
        mismatch_multiplier=0.45,
        domain_mismatch_reason="broad_catalysis_domain_mismatch",
        low_scope_reason="low_mechanism_scope_overlap",
    ),
    extraction_adapter_id="catalysis_mechanism",
    graph_adapter_id="catalysis_mechanism",
    feasibility_adapter_id=None,
)
